name = "System1D"
uuid = "d6b3d6b1-3f4e-4a5b-a2f9-1a2b3c4d5e6f"
version = "0.1.0"
authors = ["Ismael Chona Rueda<you@example.com>"]

[deps]
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
KernelDensity = "0.6.10"
Plots = "1.41.3"
Random = "1.11.0"
Revise = "3.12.3"
StatsBase = "0.34.9"
Test = "1.11.0"
